### ISSUE TITLE
PHP 8.1.16 Thread-Safe not builded

### ISSUE THREAD

**Issue by celestinoxp** [shivammathur/php-builder-windows#3]
**Describe the bug**

In builds page
https://github.com/shivammathur/php-builder-windows/releases/tag/php8.1

i can´t find php 8.1.16 thead-safe updated, i can see only non-thread-safe version updated. It happens since last week...

Normally, builds are builded every night, right?

![php](https://user-images.githubusercontent.com/41735311/218432680-6e2dfc6d-6b35-4ef4-954b-1884ae32e3a7.png)

**Operating systems**

Windows 11 (64bits)

**Comment by celestinoxp** [comment]
@shivammathur  can you confirm if exists an issue?

**Comment by shivammathur** [comment]
Yes. I will check this

**Comment by shivammathur** [comment]
Fixed in https://github.com/shivammathur/php-builder-windows/commit/f0154d99b98e02b9ed43ef33b2a0d748d992d713

**Comment by celestinoxp** [comment]
> Fixed in [f0154d9](https://github.com/shivammathur/php-builder-windows/commit/f0154d99b98e02b9ed43ef33b2a0d748d992d713)

Thank you
