### ISSUE TITLE
Visual C++ builder question

### ISSUE THREAD

**Issue by celestinoxp** [shivammathur/php-builder-windows#4]
**Describe the feature**

This is only a question. PHP 8.1 is compiled with visual c++ 2019. is there any advantage to compiling php 8.1 with a newer visual c++ version?

I use a c++ reader from https://aka.ms/vs/17/release/VC_redist.x64.exe and the supported version is between 2015 and 2022, I assume 2022 is the latest version.

Note: it's just a question from a curious person who doesn't understand anything about c++.

![image](https://user-images.githubusercontent.com/41735311/225430302-d26155f0-6c83-410e-890c-ecf5a03b600a.png)

**Comment by shivammathur** [comment]
The dependencies used to build PHP are built with vs16/vc++2019. 
https://windows.php.net/downloads/php-sdk/deps/

Once the dependencies built with vs17/vc++2022 are available we can build using that, but that will be for a new PHP version.

**Comment by celestinoxp** [comment]
> The dependencies used to build PHP are built with vs16/vc++2019. https://windows.php.net/downloads/php-sdk/deps/
> 
> Once the dependencies built with vs17/vc++2022 are available we can build using that, but that will be for a new PHP version.

I use apache compiled in vs17, via https://www.apachelounge.com/download/

- Shouldn't php team have already released the updated dependencies for php (php-sdk) vs17/vc++2022?
- Is this normal, or did php team "forget" php?

**Comment by shivammathur** [comment]
Previously this was supported by Microsoft. After that ended there is only one developer working on this in the PHP project I think, so I wouldn't say that anyone forgot.
https://externals.io/message/114751
https://externals.io/message/117494

**Comment by celestinoxp** [comment]
> Previously this was supported by Microsoft. After that ended there is only one developer working on this in the PHP project I think, so I wouldn't say that anyone forgot. https://externals.io/message/114751 https://externals.io/message/117494

can you do something like ask the php team about this issue?
I don't understand c++, but I think a build on newer software is beneficial...

**Comment by shivammathur** [comment]
Sure. I will ask around the release time of PHP 8.3. Before that it wont be updated anyway.

**Comment by celestinoxp** [comment]
> Sure. I will ask around the release time of PHP 8.3. Before that it wont be updated anyway.

Thank you

**Comment by Jan-E** [comment]
There is some movement on this front: https://github.com/php/php-sdk-binary-tools/pull/5#issuecomment-1701154192
